/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "popupChoiceSection": string|undefined
  "popupCross": string|undefined
  "popupDescr": string|undefined
  "popupInput": string|undefined
  "popupInputContainer": string|undefined
  "popupInputText": string|undefined
  "popupItem": string|undefined
  "popupItemGrayText": string|undefined
  "popupItemLine": string|undefined
  "popupItemText": string|undefined
  "popupSalaryText": string|undefined
  "popupTitle": string|undefined
  "popupTitleCrossContainer": string|undefined
  "taxBG": string|undefined
  "taxPopup": string|undefined
  "taxPopupMobile": string|undefined
  "temp": string|undefined
}
